# Generated by Django 5.0.4 on 2024-07-26 16:08

import category.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to=category.models.get_path)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryLvlOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to=category.models.get_path)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category_lvl_one',
            },
        ),
        migrations.CreateModel(
            name='CategoryLvlTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100)),
                ('descriptions', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to=category.models.get_path)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category_lvl_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorylvlone')),
            ],
            options={
                'verbose_name': 'category_lvl_two',
            },
        ),
    ]
