# Generated by Django 5.0.4 on 2024-07-26 16:08

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('product_sku', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('category_lvl_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categorylvlone')),
                ('category_lvl_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categorylvltwo')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_path)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=100)),
                ('variation_sku', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('bulk_disc', models.FloatField(default=0, null=True)),
                ('wholesale_disc', models.FloatField(default=0, null=True)),
                ('color', models.CharField(default='Random', max_length=15)),
                ('size', models.FloatField(default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to=products.models.product_image_path)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductEcommerceUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('platform', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'Tiktok')], default='Shopee', max_length=10)),
                ('craeted_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'platform')},
            },
        ),
    ]
